---

- name: Copy new td-agent-bit.conf from role's default
  template:
    src: td-agent-bit.conf.j2
    dest: "/etc/td-agent-bit/td-agent-bit.conf"
  changed_when: false
  notify:
   - restart td-agent-bit

- name: Copy additional config files
  template:
    src: additional.conf.j2
    dest: "/etc/td-agent-bit/{{ item.name }}.conf"
  with_items: "{{ fluentbit_inputs }}"
  changed_when: false
  notify:
   - restart td-agent-bit

- name: Include additional config files
  lineinfile:
    path: "/etc/td-agent-bit/td-agent-bit.conf"
    line: "@INCLUDE {{item.name}}.conf"
    state: present
  with_items: "{{ fluentbit_inputs }}"
