---
- name: Ensure rsyslog is installed
  package:
    name: rsyslog
    state: installed

- block:
  - name: Add apt key
    apt_key:
      url: http://packages.fluentbit.io/fluentbit.key
      state: present

  - name: Add repo
    apt_repository:
      repo: deb http://packages.fluentbit.io/ubuntu xenial main

  - name: Install fluentbit
    apt:
      name: td-agent-bit
      state: present
  when: ansible_pkg_mgr == "apt"

- block:
  - name: Add yum repository
    yum_repository:
      name: TD_Agent_Bit
      baseurl: http://packages.fluentbit.io/centos/7
      gpgcheck: yes
      gpgkey: http://packages.fluentbit.io/fluentbit.key
      description: fluent bit  repo
      enabled: yes

  - name: Install fluentbit
    yum:
      name: td-agent-bit
      state: present
      update_cache: yes
  when: ansible_pkg_mgr == "yum"

- name: Ensure fluentbit (td-agent-bit) service is enabled and started
  service:
    name: td-agent-bit
    state: started
    enabled: yes
